In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import nltk
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.stem import LancasterStemmer,WordNetLemmatizer
import re, string, unicodedata
from string import punctuation

In [9]:
path = '경로 지정'

In [10]:
df = pd.read_csv(path + '/text 감정 추출 모델/tweet_data_agumentation.csv').iloc[:,1:]

In [11]:
df.head()

sentiment                                            content
0          0  know wa listenin bad habit earlier start freak...
1          1              layin n bed headach ughhhhwaitin call
2          1                        funer ceremonygloomi friday
3          2                              want hang friend soon
4          4   reping whi didnt go prom bc bf didnt like friend

In [12]:
sur_index = df[df['sentiment']==5].index

In [13]:
df.drop(sur_index,axis=0,inplace=True)
df

sentiment                                            content
0              0  know wa listenin bad habit earlier start freak...
1              1              layin n bed headach ughhhhwaitin call
2              1                        funer ceremonygloomi friday
3              2                              want hang friend soon
4              4   reping whi didnt go prom bc bf didnt like friend
...          ...                                                ...
63174         10                    return ha cryopreserv mbb futur
63175         10                                ha futur may return
63176         10                mbb ha futur cryopreserv return may
63177         10                       mbb futur return cryopreserv
63178         10                futur ha mbb may return cryopreserv

[63179 rows x 2 columns]

In [14]:
df=df.reset_index().iloc[:,1:]
df

sentiment                                            content
0              0  know wa listenin bad habit earlier start freak...
1              1              layin n bed headach ughhhhwaitin call
2              1                        funer ceremonygloomi friday
3              2                              want hang friend soon
4              4   reping whi didnt go prom bc bf didnt like friend
...          ...                                                ...
63174         10                    return ha cryopreserv mbb futur
63175         10                                ha futur may return
63176         10                mbb ha futur cryopreserv return may
63177         10                       mbb futur return cryopreserv
63178         10                futur ha mbb may return cryopreserv

[63179 rows x 2 columns]

In [15]:
df['sentiment'].value_counts()

6     14977
4      8254
7      7494
11     6146
8      5539
1      5055
9      5020
0      3007
2      3003
10     2960
12     1724
Name: sentiment, dtype: int64

In [16]:
def hapus_url(text):
    mention_pattern = r'@[\w]+'
    cleaned_text = re.sub(mention_pattern, '', text)
    return re.sub(r'http\S+','', cleaned_text)
    return re.sub(r'http\S+','', text)
def remove_special_characters(text, remove_digits=True):
    pattern=r'[^a-zA-Z0-9\s]'
    text=re.sub(pattern,'',text)
    return text
def stemmer(text):
    ps=nltk.porter.PorterStemmer()
    text=' '.join([ps.stem(word) for word in text.split()])
    return text

def final_clean(text):
    final_text= []
    for i in text.split():
        if i.strip().lower() not in sw and i.strip().lower().isalpha():
            final_text.append(i.strip().lower())
    return " ".join(final_text)

In [17]:
def clean(text):
    text = hapus_url(text)
    text = remove_special_characters(text, remove_digits=True)
    text = stemmer(text)
    text = final_clean(text)
    return text

In [10]:
df.shape

(117785, 2)

# Training

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()

text1 = tfidf_vect.fit_transform(df["content"])

In [12]:
y = df["sentiment"]
y

0         0
1         1
2         1
3         2
4         4
         ..
117780    9
117781    9
117782    9
117783    6
117784    6
Name: sentiment, Length: 117785, dtype: int64

In [13]:
text1_arr = text1.toarray()
a = pd.DataFrame(text1_arr, columns=tfidf_vect.get_feature_names_out())

In [25]:
a.iloc[:, 130:150]

accountgt  accountquot  accountsand  acct  accumul  accus  accustom  \
0             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
1             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
2             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
3             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
4             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
...           ...          ...          ...   ...      ...    ...       ...   
117780        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117781        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117782        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117783        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117784        0.0          0.0          0.0   0.0      0.0    0.0       0.0   

        acdc  ace  acen  acess  acet  ach  achebut  achi  achiev  acho  \
0        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
1        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
2        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
3        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
4        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
...      ...  ...   ...    ...   ...  ...      ...   ...     ...   ...   
117780   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117781   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117782   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117783   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117784   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   

        achvstak  acid  acident  
0            0.0   0.0      0.0  
1            0.0   0.0      0.0  
2            0.0   0.0      0.0  
3            0.0   0.0      0.0  
4            0.0   0.0      0.0  
...          ...   ...      ...  
117780       0.0   0.0      0.0  
117781       0.0   0.0      0.0  
117782       0.0   0.0      0.0  
117783       0.0   0.0      0.0  
117784       0.0   0.0      0.0  

[117785 rows x 20 columns]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test = train_test_split(text1, y, test_size=0.3, random_state=123)

In [14]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report
print(X_train.shape)

(82449, 22599)


In [ ]:
model = SVC()
model.probability=True
model.fit(X_train,y_train)

In [ ]:
pred_svm = model.predict(X_test)
print(classification_report(pred_svm, y_test))

              precision    recall  f1-score   support

           0       0.73      0.98      0.84       654
           1       0.92      0.94      0.93      6194
           2       0.75      0.99      0.85       675
           4       0.97      0.86      0.91     11581
           6       0.91      0.93      0.92      4362
           7       0.86      0.98      0.92      1993
           8       0.85      0.97      0.90      1487
           9       0.94      0.90      0.92      6549
          10       0.71      0.98      0.82       169
          11       0.83      0.97      0.89      1574
          12       0.67      1.00      0.80        98

    accuracy                           0.91     35336
   macro avg       0.83      0.95      0.88     35336
weighted avg       0.92      0.91      0.91     35336



In [ ]:
pred_svm

array([4, 4, 8, ..., 6, 8, 6])

In [ ]:
y_test

13164     4
70954     4
42812     8
62776     4
80163     4
         ..
114271    9
115138    6
112086    6
46004     8
100457    6
Name: sentiment, Length: 35336, dtype: int64

In [ ]:
X_test

<12000x41297 sparse matrix of type '<class 'numpy.float64'>'
	with 89619 stored elements in Compressed Sparse Row format>

In [ ]:
df['content']

0        tiffanylu know wa listenin bad habit earlier s...
1                    layin n bed headach ughhhhwaitin call
2                              funer ceremonygloomi friday
3                                    want hang friend soon
4        dannycastillo want trade someon ha houston tic...
                               ...                        
39995                                      johnlloydtaylor
39996                                happi mother day love
39997    happi mother day mommi woman man long momma so...
39998    niariley wassup beauti follow peep new hit sin...
39999    mopedronin bullet train tokyo gf visit japan s...
Name: content, Length: 40000, dtype: object

In [ ]:
data = pd.DataFrame(['i am very happy','i am so sad','mother died today. or maybe it was yesterday, i do not know'])
data.columns = ['text']

In [ ]:
data

text
0                                    i am very happy
1                                        i am so sad
2  mother died today. or maybe it was yesterday, ...

In [ ]:
text2 = tfidf_vect.transform(data["text"])
text2

<3x22599 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
pred = model.predict_proba(text2)

In [ ]:
pred[0]

array([0.00732766, 0.45392701, 0.00389544, 0.16278967, 0.20700936,
       0.01276102, 0.08639178, 0.05660119, 0.00079312, 0.00754964,
       0.00095411])

In [ ]:
y

0         0
1         1
2         1
3         2
4         4
         ..
117780    9
117781    9
117782    9
117783    6
117784    6
Name: sentiment, Length: 117785, dtype: int64

In [4]:
import pickle
import joblib

In [ ]:
saved_model = pickle.dumps(model)

In [ ]:
model_from_pickle = pickle.loads(saved_model)

In [ ]:
model_from_pickle.predict(X_test)

array([3, 3, 4, ..., 4, 9, 3])

In [ ]:
joblib.dump(model, 'SVM.pkl')

['SVM.pkl']

In [ ]:
clf_from_joblib = joblib.load('SVM.pkl')

In [5]:
path = 'C:/Users/82109/Desktop/deep daiv. 프로젝트/text 감정 추출 모델'
df = pd.read_csv(path + '/tweet_data_agumentation.csv', index_col = 0)

model = joblib.load(path + '/SVM.pkl')
model

SVC(probability=True)

In [6]:
data = pd.DataFrame(['I am really happy','i am so sad',
                     'mother died today. or maybe it was yesterday, i do not know',
                    'You are so annoying me!!'])
data.columns = ['text']
data

text
0                                  I am really happy
1                                        i am so sad
2  mother died today. or maybe it was yesterday, ...
3                           You are so annoying me!!

In [19]:
text2 = tfidf_vect.transform(data["text"])
pred = model.predict_proba(text2)
pred

array([[8.32789261e-03, 5.09206472e-02, 4.61697540e-03, 1.37597536e-01,
        7.05978099e-01, 9.49894011e-03, 7.38799622e-03, 6.80022526e-02,
        2.92845572e-04, 7.06942872e-03, 3.07387261e-04],
       [7.21019831e-05, 7.69087521e-01, 6.31204001e-05, 2.30318767e-01,
        1.08588101e-04, 2.91506606e-05, 9.81611082e-05, 1.75390974e-04,
        3.77279748e-06, 3.52031025e-05, 8.22222138e-06],
       [2.24980905e-02, 6.30076683e-02, 8.39942956e-03, 1.98563199e-01,
        3.61739253e-01, 9.63741257e-03, 1.01037537e-02, 2.86866496e-01,
        9.67613209e-04, 3.69870164e-02, 1.23006679e-03],
       [8.32789261e-03, 5.09206472e-02, 4.61697540e-03, 1.37597536e-01,
        7.05978099e-01, 9.49894011e-03, 7.38799622e-03, 6.80022526e-02,
        2.92845572e-04, 7.06942872e-03, 3.07387261e-04]])

In [20]:
sorted_indexes = sorted(range(len(pred[0])), key=lambda x: pred[0][x], reverse=True)
print(sorted_indexes)
# 0 1 2 3 4 5 6 7 8 9 10
# 0 1 2 4 6 7 8 9 10 11 12

# 6 4 9 1 7 0 11 8 2 12 10

[4, 3, 7, 1, 5, 0, 6, 9, 2, 10, 8]


In [21]:
print(data.loc[0, 'text'])
pd.DataFrame({'prob' : pred[0],
              'sentiment': ['empty', 'sadness', 'enthusiasm', 'worry', 'love', 'fun',
                            'hate', 'happiness', 'boredom', 'relief', 'anger'],
             }).sort_values(by='prob', ascending=False)


I am really happy


prob   sentiment
4   0.705978        love
3   0.137598       worry
7   0.068002   happiness
1   0.050921     sadness
5   0.009499         fun
0   0.008328       empty
6   0.007388        hate
9   0.007069      relief
2   0.004617  enthusiasm
10  0.000307       anger
8   0.000293     boredom

In [22]:
print(data.loc[1, 'text'])
pd.DataFrame({'prob' : pred[1],
              'sentiment': ['empty', 'sadness', 'enthusiasm', 'worry', 'love', 'fun',
                            'hate', 'happiness', 'boredom', 'relief', 'anger'],
             }).sort_values(by='prob', ascending=False)


i am so sad


prob   sentiment
1   0.769088     sadness
3   0.230319       worry
7   0.000175   happiness
4   0.000109        love
6   0.000098        hate
0   0.000072       empty
2   0.000063  enthusiasm
9   0.000035      relief
5   0.000029         fun
10  0.000008       anger
8   0.000004     boredom

In [23]:
print(data.loc[2, 'text'])
pd.DataFrame({'prob' : pred[2],
              'sentiment': ['empty', 'sadness', 'enthusiasm', 'worry', 'love', 'fun',
                            'hate', 'happiness', 'boredom', 'relief', 'anger'],
             }).sort_values(by='prob', ascending=False)

mother died today. or maybe it was yesterday, i do not know


prob   sentiment
4   0.361739        love
7   0.286866   happiness
3   0.198563       worry
1   0.063008     sadness
9   0.036987      relief
0   0.022498       empty
6   0.010104        hate
5   0.009637         fun
2   0.008399  enthusiasm
10  0.001230       anger
8   0.000968     boredom

In [24]:
print(data.loc[3, 'text'])
pd.DataFrame({'prob' : pred[3],
              'sentiment': ['empty', 'sadness', 'enthusiasm', 'worry', 'love', 'fun',
                            'hate', 'happiness', 'boredom', 'relief', 'anger'],
             }).sort_values(by='prob', ascending=False)

You are so annoying me!!


prob   sentiment
4   0.705978        love
3   0.137598       worry
7   0.068002   happiness
1   0.050921     sadness
5   0.009499         fun
0   0.008328       empty
6   0.007388        hate
9   0.007069      relief
2   0.004617  enthusiasm
10  0.000307       anger
8   0.000293     boredom