In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import nltk
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.stem import LancasterStemmer,WordNetLemmatizer
import re, string, unicodedata
from string import punctuation

In [2]:
df = pd.read_csv('tweet_data_agumentation.csv').iloc[:,1:]

In [3]:
df.head()

sentiment                                            content
0          0  know wa listenin bad habit earlier start freak...
1          1              layin n bed headach ughhhhwaitin call
2          1                        funer ceremonygloomi friday
3          2                              want hang friend soon
4          4   reping whi didnt go prom bc bf didnt like friend

In [4]:
sur_index = df[df['sentiment']==5].index

In [5]:
df.drop(sur_index,axis=0,inplace=True)
df

sentiment                                            content
0               0  know wa listenin bad habit earlier start freak...
1               1              layin n bed headach ughhhhwaitin call
2               1                        funer ceremonygloomi friday
3               2                              want hang friend soon
4               4   reping whi didnt go prom bc bf didnt like friend
...           ...                                                ...
117780          9  wassup beauti follow peep new singl wwwmyspace...
117781          9  wassup wat follow peep new hit singl wwwmyspac...
117782          9  wassup beauti follow peep new hit singl wwwmys...
117783          6  bullet train gf visit vacationsightse gaijin g...
117784          6  bullet train gf tokyo visit japan sinc thursda...

[117785 rows x 2 columns]

In [6]:
df=df.reset_index().iloc[:,1:]
df

sentiment                                            content
0               0  know wa listenin bad habit earlier start freak...
1               1              layin n bed headach ughhhhwaitin call
2               1                        funer ceremonygloomi friday
3               2                              want hang friend soon
4               4   reping whi didnt go prom bc bf didnt like friend
...           ...                                                ...
117780          9  wassup beauti follow peep new singl wwwmyspace...
117781          9  wassup wat follow peep new hit singl wwwmyspac...
117782          9  wassup beauti follow peep new hit singl wwwmys...
117783          6  bullet train gf visit vacationsightse gaijin g...
117784          6  bullet train gf tokyo visit japan sinc thursda...

[117785 rows x 2 columns]

In [7]:
df['sentiment'].value_counts()

4     34645
1     21002
9     20859
6     14951
7      7521
11     6124
8      5497
2      3039
0      2954
10      738
12      455
Name: sentiment, dtype: int64

In [8]:
def hapus_url(text):
    mention_pattern = r'@[\w]+'
    cleaned_text = re.sub(mention_pattern, '', text)
    return re.sub(r'http\S+','', cleaned_text)
    return re.sub(r'http\S+','', text)
def remove_special_characters(text, remove_digits=True):
    pattern=r'[^a-zA-Z0-9\s]'
    text=re.sub(pattern,'',text)
    return text
def stemmer(text):
    ps=nltk.porter.PorterStemmer()
    text=' '.join([ps.stem(word) for word in text.split()])
    return text

def final_clean(text):
    final_text= []
    for i in text.split():
        if i.strip().lower() not in sw and i.strip().lower().isalpha():
            final_text.append(i.strip().lower())
    return " ".join(final_text)

In [9]:
def clean(text):
    text = hapus_url(text)
    text = remove_special_characters(text, remove_digits=True)
    text = stemmer(text)
    text = final_clean(text)
    return text

In [10]:
df.shape

(117785, 2)

# Training

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()

text1 = tfidf_vect.fit_transform(df["content"])

In [12]:
y = df["sentiment"]
y

0         0
1         1
2         1
3         2
4         4
         ..
117780    9
117781    9
117782    9
117783    6
117784    6
Name: sentiment, Length: 117785, dtype: int64

In [13]:
text1_arr = text1.toarray()
a = pd.DataFrame(text1_arr, columns=tfidf_vect.get_feature_names_out())

In [25]:
a.iloc[:, 130:150]

accountgt  accountquot  accountsand  acct  accumul  accus  accustom  \
0             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
1             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
2             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
3             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
4             0.0          0.0          0.0   0.0      0.0    0.0       0.0   
...           ...          ...          ...   ...      ...    ...       ...   
117780        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117781        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117782        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117783        0.0          0.0          0.0   0.0      0.0    0.0       0.0   
117784        0.0          0.0          0.0   0.0      0.0    0.0       0.0   

        acdc  ace  acen  acess  acet  ach  achebut  achi  achiev  acho  \
0        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
1        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
2        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
3        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
4        0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
...      ...  ...   ...    ...   ...  ...      ...   ...     ...   ...   
117780   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117781   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117782   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117783   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   
117784   0.0  0.0   0.0    0.0   0.0  0.0      0.0   0.0     0.0   0.0   

        achvstak  acid  acident  
0            0.0   0.0      0.0  
1            0.0   0.0      0.0  
2            0.0   0.0      0.0  
3            0.0   0.0      0.0  
4            0.0   0.0      0.0  
...          ...   ...      ...  
117780       0.0   0.0      0.0  
117781       0.0   0.0      0.0  
117782       0.0   0.0      0.0  
117783       0.0   0.0      0.0  
117784       0.0   0.0      0.0  

[117785 rows x 20 columns]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test = train_test_split(text1, y, test_size=0.3, random_state=123)

In [14]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report
print(X_train.shape)

(82449, 22599)


In [ ]:
model = SVC()
model.probability=True
model.fit(X_train,y_train)

In [ ]:
pred_svm = model.predict(X_test)
print(classification_report(pred_svm, y_test))

              precision    recall  f1-score   support

           0       0.73      0.98      0.84       654
           1       0.92      0.94      0.93      6194
           2       0.75      0.99      0.85       675
           4       0.97      0.86      0.91     11581
           6       0.91      0.93      0.92      4362
           7       0.86      0.98      0.92      1993
           8       0.85      0.97      0.90      1487
           9       0.94      0.90      0.92      6549
          10       0.71      0.98      0.82       169
          11       0.83      0.97      0.89      1574
          12       0.67      1.00      0.80        98

    accuracy                           0.91     35336
   macro avg       0.83      0.95      0.88     35336
weighted avg       0.92      0.91      0.91     35336



In [ ]:
pred_svm

array([4, 4, 8, ..., 6, 8, 6])

In [ ]:
y_test

13164     4
70954     4
42812     8
62776     4
80163     4
         ..
114271    9
115138    6
112086    6
46004     8
100457    6
Name: sentiment, Length: 35336, dtype: int64

In [ ]:
X_test

<12000x41297 sparse matrix of type '<class 'numpy.float64'>'
	with 89619 stored elements in Compressed Sparse Row format>

In [ ]:
df['content']

0        tiffanylu know wa listenin bad habit earlier s...
1                    layin n bed headach ughhhhwaitin call
2                              funer ceremonygloomi friday
3                                    want hang friend soon
4        dannycastillo want trade someon ha houston tic...
                               ...                        
39995                                      johnlloydtaylor
39996                                happi mother day love
39997    happi mother day mommi woman man long momma so...
39998    niariley wassup beauti follow peep new hit sin...
39999    mopedronin bullet train tokyo gf visit japan s...
Name: content, Length: 40000, dtype: object

In [ ]:
data = pd.DataFrame(['i am very happy','i am so sad','mother died today. or maybe it was yesterday, i do not know'])
data.columns = ['text']

In [ ]:
data

text
0                                    i am very happy
1                                        i am so sad
2  mother died today. or maybe it was yesterday, ...

In [ ]:
text2 = tfidf_vect.transform(data["text"])
text2

<3x22599 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
pred = model.predict_proba(text2)

In [ ]:
pred[0]

array([0.00732766, 0.45392701, 0.00389544, 0.16278967, 0.20700936,
       0.01276102, 0.08639178, 0.05660119, 0.00079312, 0.00754964,
       0.00095411])

In [ ]:
y

0         0
1         1
2         1
3         2
4         4
         ..
117780    9
117781    9
117782    9
117783    6
117784    6
Name: sentiment, Length: 117785, dtype: int64

In [ ]:
import pickle
import joblib

In [ ]:
saved_model = pickle.dumps(model)

In [ ]:
model_from_pickle = pickle.loads(saved_model)

In [ ]:
model_from_pickle.predict(X_test)

array([3, 3, 4, ..., 4, 9, 3])

In [ ]:
joblib.dump(model, 'SVM.pkl')

['SVM.pkl']

In [ ]:
clf_from_joblib = joblib.load('SVM.pkl')